server:
  port: 9001
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: system
    password: 123
mybatis:
  mapper-locations: classpath*:mapping/*Mapper.xml
  type-aliases-package: com.ttttt.demo.pojo